default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV['DATABASE_POOL'] || 5 %>

development:
  <<: *default
  database: manage_pharma_development
  username: postgres
  password: postgres

test: &test
  <<: *default
  database: manage_pharma_test
  username: postgres
  password: postgres


production:
  <<: *default
  database: manage_pharma_production